export type CropMode = "center-crop" | "fit-inside" | "fill";

export type Size = {
  readonly width: number;
  readonly height: number;
};

export type Rect = {
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
};

export type CropOrFitPlan = {
  readonly source: Rect;
  readonly destination: Rect;
  readonly fillsTargetCanvas: boolean;
};

/**
 * Computes how the source image should be sampled before high-quality resize.
 *
 * Real early-web and early-device output was low-pixel, but it was not normally
 * generated by nearest-neighbor sampling. Keeping the crop and fit math explicit
 * makes it easier to avoid accidental jagged edges in UI and worker code.
 */
export function computeCropOrFitPlan(
  source: Size,
  target: Size,
  cropMode: CropMode,
): CropOrFitPlan {
  const sourceRatio = source.width / source.height;
  const targetRatio = target.width / target.height;

  if (cropMode === "fit-inside") {
    const scale = Math.min(
      target.width / source.width,
      target.height / source.height,
    );
    const width = source.width * scale;
    const height = source.height * scale;

    return {
      source: { x: 0, y: 0, width: source.width, height: source.height },
      destination: {
        x: (target.width - width) / 2,
        y: (target.height - height) / 2,
        width,
        height,
      },
      fillsTargetCanvas: false,
    };
  }

  if (cropMode === "fill") {
    return {
      source: { x: 0, y: 0, width: source.width, height: source.height },
      destination: { x: 0, y: 0, width: target.width, height: target.height },
      fillsTargetCanvas: true,
    };
  }

  if (sourceRatio > targetRatio) {
    const width = source.height * targetRatio;

    return {
      source: {
        x: (source.width - width) / 2,
        y: 0,
        width,
        height: source.height,
      },
      destination: { x: 0, y: 0, width: target.width, height: target.height },
      fillsTargetCanvas: true,
    };
  }

  const height = source.width / targetRatio;

  return {
    source: {
      x: 0,
      y: (source.height - height) / 2,
      width: source.width,
      height,
    },
    destination: { x: 0, y: 0, width: target.width, height: target.height },
    fillsTargetCanvas: true,
  };
}
